# Generated by Django 5.1 on 2024-09-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='patient',
            field=models.TextField(),
        ),
    ]
